### PR TITLE
Handle next served on ft.com

### PR DESCRIPTION
**Pull request by StuartFT**
next.ft.com can also now be accessed through an ft.com domain. This broke the lantern chrome extension but this change should fix it.

### CODE REVIEW

**Comment by Lucas-Gluchowski** [comment]
.gitignore file could be a bit more concise. For instance just point to /idea folder instead of pointing all files int that folder. Is JIRA integration file necessary, etc.

**Comment by StuartFT** [comment]
modified above .git ignore removing a lot of fluff.

**Comment by matthew-andrews** [comment]
👯

**Comment by Lucas-Gluchowski** [comment]
👍

**Pull request merged**
